apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: nanil0034/notes-app:11
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for MySQL to be ready..."
              # Wait for MySQL service
              while ! nc -z mysql-service 3306; do
                sleep 1
              done
              echo "MySQL is ready!"
              
              echo "Running migrations..."
              cd /app/backend && python manage.py migrate --noinput
              
              echo "Starting Gunicorn..."
              cd /app/backend && exec gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000 --workers=2 --access-logfile -
          env:
            - name: DATABASE_HOST
              value: "mysql-service"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "test_db"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
            - name: DJANGO_SETTINGS_MODULE
              value: "notesapp.settings"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
