apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: nanil0034/notes-app:54
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for MySQL to be ready..."
              sleep 30
              echo "Starting Django application..."
              python manage.py migrate --noinput || echo "Migration failed"
              echo "Starting Gunicorn..."
              gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000 --workers=2 --log-level=debug
          env:
            - name: DATABASE_HOST
              value: "mysql-service"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "test_db"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"  # সরাসরি value দিন (Secret থেকে নেওয়া কাজ করছে না)
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Optional: specify a port (30000-32767)
  type: NodePort
