apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: nanil0034/notes-app:54
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args:
            - |
              echo "Starting Django application..."
              python manage.py migrate --noinput || echo "Migration failed"
              echo "Starting Gunicorn..."
              gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000 --workers=2 --log-level=debug
          envFrom:
            - configMapRef:
                name: django-env-config
          # Add resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
